### ISSUE TITLE
Bundling for npm not available

### ISSUE THREAD

**Issue by Ledragon** [SamVerschueren/angular2-polyfill#28]
Hi,
First, thanks for the great idea, this library seems like it could help me with my current problem, i.e. upgrading my routes from ui-router to using the new router (I am currently in a hybrid app).

However, installing the package from npm, I saw that all files were available (including TypeScript), but not the bundled js file. Is it normal, as you consider it is too early to provide the bundle? Could I help with that?

**Comment by SamVerschueren** [comment]
Hi @Ledragon. First of all, thanks for using it. Would love to receive feedback from others :).

I just tested it with `angular2` and they indeed ship the bundle with `npm` as well. I did not release a version with a bundle yet as I just created the gulpfile yesterday. Are you using `jspm` or something to install your dependencies? It should work with `jspm install npm:angular2-polyfill` though. But I will release the bundle one of the following days.

**Comment by Ledragon** [comment]
I installed with a classic `npm install angular2-polyfill`.  Here is the ouput I got:

![polyfill](https://cloud.githubusercontent.com/assets/9558809/13729490/6cf1b62a-e936-11e5-864f-6017286f0a6d.png)

**Comment by SamVerschueren** [comment]
That's indeed the output of a normal `npm install`. Your workflow is then to just import the bundle script in `index.html`?

This is an example with using JSPM: [Tour of Heroes](https://github.com/SamVerschueren/angular2-polyfill-heroes).

**Comment by Ledragon** [comment]
Yep, I simply reference the file in my `index.html`, not quite used to jspm (nor module loaders, noob on systemjs). So using the bundled file is easier for me.

**Comment by SamVerschueren** [comment]
@Ledragon The bundle is available on npm in `v0.0.18`.
