### ISSUE TITLE
Missing peer dependencies after installed angular2 rc-6

### ISSUE THREAD

**Issue by bigdaddyrus** [SamVerschueren/angular2-polyfill#54]
After I updated angular2 to rc-6 this morning, polyfill is complaining that its missing rxjs@5.0.0-beta.6.

├── chart.js@2.2.2
├── http@0.0.0
└─┬ UNMET PEER DEPENDENCY rxjs@5.0.0-beta.11
  └── symbol-observable@1.0.2

npm WARN angular2-polyfill@0.0.32 requires a peer of rxjs@5.0.0-beta.6 but none was installed.

But then if I install  rxjs@5.0.0-beta.6, angular2-rc-6 complains about beta.6 and requires 11
├── chart.js@2.2.2
├── http@0.0.0
└── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.6

npm WARN @angular/core@2.0.0-rc.6 requires a peer of rxjs@5.0.0-beta.11 but none was installed.
npm WARN @angular/http@2.0.0-rc.6 requires a peer of rxjs@5.0.0-beta.11 but none was installed.
npm WARN @angular/router@3.0.0-rc.2 requires a peer of rxjs@5.0.0-beta.11 but none was installed.

Is there a way to work around this? Thanks!

**Comment by SamVerschueren** [comment]
Just wondering, why are you using the polyfill together with Angular2? Might have missed a use case myself though, so just asking :).

**Comment by bigdaddyrus** [comment]
I actually don't rememver how it got in here. I'm trying to remove it and see if my application still works. Thanks for the reply

**Comment by SamVerschueren** [comment]
If you are running fully on Angular2, this project is of no use. It's a polyfill for writing Angular2-like code for Angular1.

Closing this for now, let me know if you actually need it and I can look into it.
